---
- name: install utilities
  hosts: all
  tasks:
    - name: create a file with some dynamic values
      ansible.builtin.template:
        src: info.txt.j2
        dest: /tmp/info.txt
    
        