---
- hosts: webserver
  become: yes
  tasks:
  - name: update packages
    apt:
      update_cache: yes
  - name: install apache
    apt:
      name: apache2
      state: present
  - name: Create the home page
    file:
      path: /home/ansible/index.html
      state: file
  - name: stop apache
    service:
      name: apache2
      state: stopped
  - name: Copy the Home Page to server
    file:
      src: /home/ansible/index.html
      dest: /var/www/html/index.html
  - name: Start the apache
    service: 
      name: apache2
      state: started
