---
- name: install tomcat 9
  become: yes
  hosts: appserver
  vars:
    tomcat_home_dir: /opt/tomcat
    tomcat_user: tomcat
    tomcat_default_shell: /bin/false
    tomcat_download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
    tomcat_download_location: /tmp/apache-tomcat-9.0.65.tar.gz
  tasks:
    - name: update ubuntu packages and install java 11
      ansible.builtin.apt:
        name: "{{ java_package_name }}"
        update_cache: yes
        state: present
    - name: Create a system user
      ansible.builtin.user:
        name: "{{ tomcat_user }}"
        create_home: yes
        home: "{{ tomcat_home_dir }}"
        shell: "{{ tomcat_default_shell }}"
    - name: download tomcat
      ansible.builtin.get_url:
        url: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_download_location }}"
    - name: extract tomcat
      ansible.builtin.unarchive:
        src: "{{ tomcat_download_location }}"
        dest: "{{ tomcat_home_dir }}"
        remote_src: yes
    - name: create symbolic link
      ansible.builtin.file:
        src: "{{ tomcat_home_dir }}/apache-tomcat-9.0.65"
        dest: "{{ tomcat_home_dir }}/latest"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        state: link
    - name: Recursively change ownership of a tomcat home directory 
      ansible.builtin.file:
        path: "{{ tomcat_home_dir }}"
        state: directory
        recurse: yes
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"