---
- name: activity 2 - install php
  become: yes
  hosts: webservers
  vars:
    
  tasks:
    - name: fail on unsupported operating systems
      ansible.builtin.fail:
        msg: "This playbook will work on Debian and RedHat Only"
      when: ansible_facts["os_family"] != "Debian" and ansible_facts["os_family"] != "RedHat"
    - name: print value
      ansible.builtin.debug:
        var: all_packages
    - name: install apache
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ all_packages }}"
    - name: create info.php
      ansible.builtin.copy:
        content: '<?php phpinfo(); ?>'
        dest: /var/www/html/info.php
    - name: ensure httpd is running
      ansible.builtin.service:
        name: "{{ package_name }}"
        enabled: yes
        state: started