---
- name: installing tomcat
  hosts: appserver
  become: yes
  vars:
    username: tomcat
    java_package: openjdk-8-jdk
  vars_files:
    - vars/tomcat_ubuntu_vars.yaml
  tasks:
    - name: install java on ubuntu
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: add tomcat group
      group:
        name: "{{ username }}"
        state: present
    - name: add tomcat user
      user:
        name: "{{ username }}"
        home: "{{ tomcat_install_path }}"
        group: "{{ username }}"
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: download tomcat
      get_url:
        url: "{{ tomcat_download_source }}"
        dest: "{{ tomcat_download_location }}"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: extract tomcat
      unarchive:
        src: "{{ tomcat_download_location }}"
        dest: "{{ tomcat_install_path }}"
      when: ansible_facts['distribution'] == "Ubuntu"
      

      
