---
- hosts: all
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
  - name: start httpd
    service:
       name: httpd
       enabled: yes
       state: started
  - name: install php packages
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-mysql
  - name: restart apache
    service:
      name: httpd
      state: restarted
